/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-09 04:26:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.*;
import review.model.service.*;
import review.model.vo.*;
import javax.servlet.http.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1560042249556L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1559717494180L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("user.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("review.model.service");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("review.model.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" <html>\n");
      out.write(" <head>\n");
      out.write(" <script>\n");
      out.write("(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n");
      out.write("(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n");
      out.write("m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n");
      out.write("})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n");
      out.write("ga('create', 'UA-128561305-2', 'auto');\n");
      out.write("ga('send', 'pageview');\n");
      out.write("</script>\n");
      out.write(" <meta charset=\"UTF-8\">\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write(" <title>Welcome, BambooReview</title>\n");
      out.write("\n");
      out.write("  <!--------------------Full page--------------------------->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/slider.js\"></script>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/slider.css\" />\n");
      out.write("  <!----------------------------------------------->\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/backgroundTransition.css\" />\n");
      out.write("  \n");
      out.write(" </head>\n");
      out.write(" \n");
      out.write("  <body>\n");
      out.write("    <div class=\"slides\">\n");
      out.write("      <section id=\"first\">\n");
      out.write("      \t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	ReviewService service = new ReviewService();
	//Cookie[] cookies = request.getCookies();
	boolean saveIdFlag = false;
	String userId = "";
 	/////////////////////////////////쿠키문제////////////////////////
	/* if(cookies != null){
		for(Cookie c: cookies){
			String key = c.getName();
			String value = c.getValue();
			if("saveId".equals(key)){
				saveIdFlag = true;
				userId = value;
			}
		}
	} */
	////////////////////////////////////////////////////////////

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <script>\r\n");
      out.write("(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n");
      out.write("(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n");
      out.write("m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n");
      out.write("})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\r\n");
      out.write("ga('create', 'UA-128561305-2', 'auto');\r\n");
      out.write("\r\n");
      out.write("if (document.location.pathname.indexOf('/user') > -1 ||\r\n");
      out.write("\t\tdocument.location.pathname.indexOf('/price') > -1 ||\r\n");
      out.write("\t\tdocument.location.pathname.indexOf('/review') > -1 ||\r\n");
      out.write("\t\tdocument.location.pathname.indexOf('/hotel') > -1) {\r\n");
      out.write("\t  var pathArr = document.location.pathname.split('/');\r\n");
      out.write("\r\n");
      out.write("\t  var page = \"/\"+pathArr[1]+\"/\"+pathArr[2];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  // Sets the page value on the tracker.\r\n");
      out.write("\t  ga('set', 'page', page);\r\n");
      out.write("\r\n");
      out.write("\t  // Sending the pageview no longer requires passing the page\r\n");
      out.write("\t  // value since it's now stored on the tracker object.\r\n");
      out.write("\t  ga('send', 'pageview');\r\n");
      out.write("\t}\r\n");
      out.write("ga('send', 'pageview');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <!-- 시맨틱 UI -->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css\"/>\r\n");
      out.write(" <!----------------------------------------------->  \r\n");
      out.write(" \r\n");
      out.write(" <!--------------------JQuery--------------------------->\r\n");
      out.write(" <script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <!----------------------------------------------->\r\n");
      out.write(" \r\n");
      out.write("  <!--bootstrap-->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <!----------------------------------------------->\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"ui menu\" style=\"background-color:#68b30d; opacity: 0.8; height:67px; width:1024px;\">\r\n");
      out.write("\r\n");
      out.write("  \t\t<div class=\"header item\">\r\n");
      out.write("    \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\" class=\"home-logo\"><img style= \"height:68px\"src=\"");
      out.print(request.getContextPath());
      out.write("/images/bambooHeader.png\"></a>\r\n");
      out.write(" \t\t</div>\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t");
if(userLoggedIn==null){
      out.write("\r\n");
      out.write(" \t\t<a data-event-category=\"User\"\r\n");
      out.write("  \t\t\tdata-event-action=\"Price\" class=\"item right\" href=\"");
      out.print(request.getContextPath());
      out.write("/price/priceInfo\">\r\n");
      out.write("   \t\t\t가격정보\r\n");
      out.write("  \t\t</a>\r\n");
      out.write("  \t\t<a data-event-category=\"User\"\r\n");
      out.write("  \t\t\tdata-event-action=\"signout\" class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userLogin\">\r\n");
      out.write("    \t\t로그인\r\n");
      out.write("  \t\t</a>\r\n");
      out.write(" \t\t");
} else if(userLoggedIn!=null && "A".equals(userLoggedIn.getStatus())){
      out.write("\r\n");
      out.write(" \t\t\t<a class=\"item right\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminList\">\r\n");
      out.write("  \t\t\t\t 관리자페이지\r\n");
      out.write(" \t\t\t</a>\t\t\r\n");
      out.write(" \t\t\t<a class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userView?email=");
      out.print(userLoggedIn.getEmail());
      out.write("\">\r\n");
      out.write("   \t\t\t\t내 정보 보기\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write("  \t\t\t<a class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/price/priceInfo\">\r\n");
      out.write("   \t\t\t\t가격정보\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write("  \t\t\t<a class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userLogout\" onclick=\"signOut();\">\r\n");
      out.write("    \t\t\t로그아웃하기\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write(" \t\t");
}else{
      out.write("\r\n");
      out.write(" \t\t<a class=\"item right\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminList\" style=\"visibility:hidden;\" id=\"admin-board\">\r\n");
      out.write("  \t\t\t\t 관리자페이지\r\n");
      out.write(" \t\t\t</a>\t\t\r\n");
      out.write(" \t\t\t<a class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userView?email=");
      out.print(userLoggedIn.getEmail());
      out.write("\">\r\n");
      out.write("   \t\t\t\t내 정보 보기\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write("  \t\t\t<a class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/price/priceInfo\">\r\n");
      out.write("   \t\t\t\t가격정보\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write("  \t\t\t<a class=\"item\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userLogout\" onclick=\"signOut();\">\r\n");
      out.write("    \t\t\t로그아웃하기\r\n");
      out.write("  \t\t\t</a>\r\n");
      out.write(" \t\t");
}
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://apis.google.com/js/api.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("gapi.load('auth2', function() {\r\n");
      out.write("\t  auth2 = gapi.auth2.init({\r\n");
      out.write("\t    client_id: '1048068622103-udnmctl1b1p2p8g9tqtcaflcb3c7p1e7.apps.googleusercontent.com',\r\n");
      out.write("\t    scope: 'email'\r\n");
      out.write("\t  }).then(()=>{\r\n");
      out.write("\t\t  console.log('fetched perfectly!')\r\n");
      out.write("\t\t  })\r\n");
      out.write("})\r\n");
      out.write("function signOut() {\r\n");
      out.write("   var auth2 = gapi.auth2.getAuthInstance();\r\n");
      out.write("   auth2.signOut().then(function () {\r\n");
      out.write("     console.log('User signed out.');\r\n");
      out.write("   });\r\n");
      out.write(" }\r\n");
      out.write(" </script>\r\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<!--------------------Scroll page--------------------------->\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/backgroundTransition.js\"></script>\n");
      out.write("\t<!----------------------------------------------->\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"div1\"></div>\n");
      out.write("\t\t<div class=\"backgroundTransition\"></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<img src=\"/BambooReview/images/bamboo.png\" id=\"page1-logo\" />\n");
      out.write("      \t<span id=\"page1-intro\">전세계 모든 숙박 시설에  <br>대해 솔직하고 믿을 수 있는 <br> 후기를 남길 수 있는 리뷰 커뮤니티</span>\n");
      out.write("      </section>\n");
      out.write("      \n");
      out.write("      <section id=\"second\">\n");
      out.write("      \t<div class=\"div2\"></div>\n");
      out.write("      \t<span>숙박후기, 여기서 보세요!</span>\n");
      out.write("      \t<div class=\"ui category search\" id=\"search-location\">\n");
      out.write(" \t\t\t <div class=\"ui icon input\"> \t\t\t \t\n");
      out.write("    \t\t\t<input id=\"srch-input\" class=\"prompt\" type=\"text\" placeholder=\"Search location...\" name=\"srch-input\">\n");
      out.write("    \t\t\t<i class=\"search icon\"></i>\n");
      out.write(" \t\t\t</div>\n");
      out.write(" \t\t\t <div class=\"results\"></div>\n");
      out.write(" \t\t</div>\n");
      out.write(" \t\t<button class=\"ui green button\" id=\"searh-button\"><i class=\"search icon\"></i>search</button>\n");
      out.write(" \t\t <form action=\"");
      out.print(request.getContextPath());
      out.write("/hotel/hotelList?srchword=london\"\n");
      out.write("      \t\t\t\tname=\"hotelDataFrm\" id=\"hotelDataFrm\" method=\"get\">\n");
      out.write("    \t\t\t<input type=\"hidden\" name=\"srchword\" id=\"srchword\">\n");
      out.write("      \t\t\t<input type=\"hidden\" name=\"userId\" id=\"userId\" value=\"");
      out.print(userLoggedIn );
      out.write("\"/>\n");
      out.write("       \t\t\t<input type=\"hidden\" name=\"hotelData\" id=\"hotelData\"/>\n");
      out.write("   \t\t</form>\n");
      out.write(" \t\t\n");
      out.write("      </section>\n");
      out.write("      \n");
      out.write("      <section id=\"third\" class=\"animated\">\n");
      out.write("    \t <!--1번-->\n");
      out.write("      \t<div class=\"card mb-3\" id=\"main-card1\">\n");
      out.write("  \t\t\t\t<div class=\"row no-gutters\">\n");
      out.write("    \t\t\t\t<div class=\"col-md-4\">\n");
      out.write("      \t\t\t\t\t<img src=\"/BambooReview/images/main-review1.jpg\" class=\"main-review\">\n");
      out.write("    \t\t\t\t</div>\n");
      out.write("    \t\t\t\t<div class=\"col-md-8\">\n");
      out.write("      \t\t\t\t\t<div class=\"card-body\">\n");
      out.write("        \t\t\t\t\t<h5 class=\"card-title\">깨끗하고 좋았습니다</h5>\n");
      out.write("        \t\t\t\t\t<p class=\"card-text\">가격도 저렴하고 시설도 깨끗했습니다. 위치도 좋아서 대중교통 이용하기도 편합니다!</p>\n");
      out.write("        \t\t\t\t\t<p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\n");
      out.write("      \t\t\t\t\t</div>\n");
      out.write("    \t\t\t\t</div>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--2번-->\n");
      out.write("\t\t<div class=\"card mb-3\"  id=\"main-card2\">\n");
      out.write("  \t\t\t\t<div class=\"row no-gutters\">\n");
      out.write("    \t\t\t\t<div class=\"col-md-4\">\n");
      out.write("      \t\t\t\t\t<img src=\"/BambooReview/images/main-review2.jpg\" class=\"main-review\">\n");
      out.write("    \t\t\t\t</div>\n");
      out.write("    \t\t\t<div class=\"col-md-8\">\n");
      out.write("      \t\t\t\t<div class=\"card-body\">\n");
      out.write("        \t\t\t\t<h5 class=\"card-title\">전망이 좋아요!</h5>\n");
      out.write("        \t\t\t\t<p class=\"card-text\">조식도 맛있고, 직원분들도 친절하십니다. 또 가고 싶네요</p>\n");
      out.write("        \t\t\t\t<p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\n");
      out.write("      \t\t\t\t</div>\n");
      out.write("    \t\t\t</div>\n");
      out.write("  \t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!--3번-->\n");
      out.write("\t\t<div class=\"card mb-3\" id=\"main-card3\">\n");
      out.write("  \t\t\t\t<div class=\"row no-gutters\">\n");
      out.write("    \t\t\t\t<div class=\"col-md-4\">\n");
      out.write("      \t\t\t\t\t<img src=\"/BambooReview/images/main-review3.jpg\" class=\"main-review\">\n");
      out.write("    \t\t\t\t</div>\n");
      out.write("    \t\t\t<div class=\"col-md-8\">\n");
      out.write("      \t\t\t\t<div class=\"card-body\">\n");
      out.write("        \t\t\t\t<h5 class=\"card-title\">깨끗하고 좋았습니다</h5>\n");
      out.write("        \t\t\t\t<p class=\"card-text\">가격도 저렴하고 시설도 깨끗했습니다. 위치도 좋아서 대중교통 이용하기도 편합니다!</p>\n");
      out.write("        \t\t\t\t<p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\n");
      out.write("      \t\t\t\t</div>\n");
      out.write("    \t\t\t</div>\n");
      out.write("  \t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"div3\"></div>\n");
      out.write("\t\t<span>유저 후기로 인증된 <br>신뢰 1위 커뮤니티</span>\n");
      out.write("      </section>\n");
      out.write("      \n");
      out.write("      <section id=\"fourth\">\n");
      out.write("\t\t<div class=\"div4\"></div>\n");
      out.write("      \t<span class=\"adver1\">숙박 광고를 위한<br> 최고의 파트너  </span>\n");
      out.write("      \t<span class=\"adver2\">여행을 계획하고있는 수많은 고객이 방문하는 <br>BamBooReview에서 최상의 광고효과를 얻을 수 있습니다!  </span>\n");
      out.write("      \t<div class=\"card\" id=\"thanos\">\n");
      out.write("\t  \t\t<img src=\"/BambooReview/images/thanos.jpg\" class=\"card-img-top\">\n");
      out.write("\t  \t\t<div class=\"card-body\">\n");
      out.write("\t    \t<p class=\"card-text\">Team Thanos. contact:ageg123@naver.com</p>\n");
      out.write("\t  \t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"ui menu\" style=\"position:absolute; background-color:#68b30d; height:2.5rem; bottom:0; width:100%\">\r\n");
      out.write("  <div style=\"position:absolute; left:34%; top:6px; width:1024px;\">\r\n");
      out.write("    <p style=\"font-size:17px;\">&lt;Copyright 2019. Team Thanos. All rights reserved.&gt;</p>\r\n");
      out.write("  </div>");
      out.write("\n");
      out.write("      </section>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    slider('.slides');\n");
      out.write("    $(document).ready(function(){\n");
      out.write("\t  $('.backgroundTransition').backgroundTransition({\n");
      out.write("\t\t  backgrounds:[\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back1.jpg\" },\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back2.jpg\" },\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back3.jpg\" },\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back4.jpg\" },\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back5.jpg\" },\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back6.jpg\" },\n");
      out.write("\t\t\t  { src: \"");
      out.print(request.getContextPath());
      out.write("/images/main-back7.jpg\" }\n");
      out.write("\t\t  ],\n");
      out.write("\t\t  transitionDelay: 2,\n");
      out.write("\t\t  animationSpeed: 400\n");
      out.write("\t  });\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("$(\"#searh-button\").click(function(){\n");
      out.write("\tif($(\"#userId\").val()==\"null\"){\n");
      out.write("\t\treturn alert(\"로그인후 사용해주세요.\")\n");
      out.write("\t}\n");
      out.write("\tif($(\"#srch-input\").val()==''){\n");
      out.write("\t\t$(\"#srch-input\").val(\"london\")\n");
      out.write("\t}\n");
      out.write("\tparam = {keyword:$(\"#srch-input\").val()}\n");
      out.write("\t\n");
      out.write("\t$.ajax({\n");
      out.write("\turl: \"");
      out.print(request.getContextPath());
      out.write("/hotel/hotelInfo\",\n");
      out.write("\tdataType: \"json\",\n");
      out.write("\tdata:param,\n");
      out.write("\tsuccess: function(data){\n");
      out.write("\t    Arr =[];\n");
      out.write("        for(var i=0; i<5; i++){\n");
      out.write("            hotel = {};\n");
      out.write("            hotel.id = data.results[i].place_id\n");
      out.write("            hotel.name = data.results[i].name\n");
      out.write("            if(data.results[i].photos){\n");
      out.write("            hotel.photo = data.results[i].photos[0].photo_reference}\n");
      out.write("            hotel.address = data.results[i].formatted_address\n");
      out.write("            hotel.rate = data.results[i].rating\n");
      out.write("            hotel.info = data.results[i].types\n");
      out.write("            Arr.push(hotel)\n");
      out.write("             var json = JSON.stringify(Arr);\n");
      out.write("              $(\"#hotelData\").val(json)\n");
      out.write("       \t\t$(\"#srchword\").val($(\"#srch-input\").val())\n");
      out.write("              $(\"#hotelDataFrm\").submit()\n");
      out.write("        }\n");
      out.write("\t},\n");
      out.write("\terror:function(jqxhr, textStatus, errorThrown){\n");
      out.write("        console.log(\"ajax처리실패!\")\n");
      out.write("        console.log(jqxhr);\n");
      out.write("         console.log(textStatus);\n");
      out.write("         console.log(errorThrown);\n");
      out.write("    }\n");
      out.write("\t});\n");
      out.write("})\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("    </script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
