/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-05-29 07:50:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1559112869475L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1559112868245L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html onresize=\"parent.resizeTo(1024,768)\" onload=\"parent.resizeTo(1024,768)\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>BamBoo Review</title>\r\n");
      out.write("    <script src=\"slider.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"slider.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 시맨틱 UI -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"Semantic/semantic.css\">\r\n");
      out.write("\t<script\r\n");
      out.write("  \t\tsrc=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("  \t\tintegrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write(" \t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"Semantic/semantic.js\"></script>\r\n");
      out.write("\t<!----------------------------------------------->\r\n");
      out.write("\t<!--bootstrap-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!----------------------------------------------->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"demo.css\" />\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"backgroundTransition.css\" />\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"backgroundTransition.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("  <div style=\"width:1024px;\" align=\"center\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("    <div class=\"slides\">\r\n");
      out.write("\t<section id=\"norwegian\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"slider.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"home\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminList\">관리자 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"notice\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/price/priceInfo\">가격정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"board\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberInfo\">내 정보보기</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"board\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberLoggedIn\">로그인</a></li>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t<!-- \t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\" >\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">Navbar</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavAltMarkup\" aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\r\n");
      out.write("    <div class=\"navbar-nav\">\r\n");
      out.write("      <a class=\"nav-item nav-link active\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      <a class=\"nav-item nav-link\" href=\"#\">Features</a>\r\n");
      out.write("      <a class=\"nav-item nav-link\" href=\"#\">Pricing</a>\r\n");
      out.write("      <a class=\"nav-item nav-link disabled\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">Disabled</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav> -->\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("\t<div class=\"div1\"></div>\r\n");
      out.write("\t\t<div class=\"backgroundTransition\"></div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t  $(document).ready(function(){\r\n");
      out.write("\t\t\t  $('.backgroundTransition').backgroundTransition({\r\n");
      out.write("\t\t\t\t  backgrounds:[\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back1.jpg\" },\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back2.jpg\" },\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back3.jpg\" },\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back4.jpg\" },\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back5.jpg\" },\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back6.jpg\" },\r\n");
      out.write("\t\t\t\t\t  { src: \"/BambooReview/images/main-back7.jpg\" }\r\n");
      out.write("\t\t\t\t  ],\r\n");
      out.write("\t\t\t\t  transitionDelay: 2,\r\n");
      out.write("\t\t\t\t  animationSpeed: 400\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t</script>\r\n");
      out.write("      \t\t<img src=\"/BambooReview/images/bamboo.png\" id=\"page1-logo\" />\r\n");
      out.write("      \t\t<span id=\"page1-intro\">전세계 모든 숙박 시설에 대해 솔직하고 믿을 수 있는 후기를 남길 수 있는 리뷰 커뮤니티</span>\r\n");
      out.write("      \t\t\r\n");
      out.write("      </section>\r\n");
      out.write("      <section id=\"french\">\r\n");
      out.write("      \t<div class=\"div2\"></div>\r\n");
      out.write("      \t<span>숙박후기, 여기서 보세요!</span>\r\n");
      out.write("      \t\t<div class=\"ui category search\" id=\"search-location\">\r\n");
      out.write(" \t\t\t \t<div class=\"ui icon input\">\r\n");
      out.write("    \t\t\t<input class=\"prompt\" type=\"text\" placeholder=\"Search location...\">\r\n");
      out.write("    \t\t\t<i class=\"search icon\"></i>\r\n");
      out.write(" \t\t\t\t</div>\r\n");
      out.write(" \t\t\t \t<div class=\"results\"></div>\r\n");
      out.write(" \t\t\t </div>\r\n");
      out.write(" \t\t\t <button class=\"ui green button\" id=\"searh-button\">search</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("      <section id=\"spanish\">\r\n");
      out.write("      <!--1번-->\r\n");
      out.write("      \t<div class=\"card mb-3\" style=\"max-width: 540px;\" id=\"main-card1\">\r\n");
      out.write("  \t\t\t\t<div class=\"row no-gutters\">\r\n");
      out.write("    \t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("      \t\t\t\t\t<img src=\"/BambooReview/images/main-review1.jpg\" class=\"main-review\">\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-md-8\">\r\n");
      out.write("      \t\t\t\t<div class=\"card-body\">\r\n");
      out.write("        \t\t\t\t<h5 class=\"card-title\">깨끗하고 좋았습니다</h5>\r\n");
      out.write("        \t\t\t\t<p class=\"card-text\">가격도 저렴하고 시설도 깨끗했습니다. 위치도 좋아서 대중교통 이용하기도 편합니다!</p>\r\n");
      out.write("        \t\t\t\t<p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--2번-->\r\n");
      out.write("\t\t<div class=\"card mb-3\" style=\"max-width: 540px;\" id=\"main-card2\">\r\n");
      out.write("  \t\t\t\t<div class=\"row no-gutters\">\r\n");
      out.write("    \t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("      \t\t\t\t\t<img src=\"/BambooReview/images/main-review2.jpg\" class=\"main-review\">\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-md-8\">\r\n");
      out.write("      \t\t\t\t<div class=\"card-body\">\r\n");
      out.write("        \t\t\t\t<h5 class=\"card-title\">전망이 좋아요!</h5>\r\n");
      out.write("        \t\t\t\t<p class=\"card-text\">조식도 맛있고, 직원분들도 친절하십니다. 또 가고 싶네요</p>\r\n");
      out.write("        \t\t\t\t<p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--3번-->\r\n");
      out.write("\t\t<div class=\"card mb-3\" style=\"max-width: 540px;\" id=\"main-card3\">\r\n");
      out.write("  \t\t\t\t<div class=\"row no-gutters\">\r\n");
      out.write("    \t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("      \t\t\t\t\t<img src=\"/BambooReview/images/main-review3.jpg\" class=\"main-review\">\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-md-8\">\r\n");
      out.write("      \t\t\t\t<div class=\"card-body\">\r\n");
      out.write("        \t\t\t\t<h5 class=\"card-title\">깨끗하고 좋았습니다</h5>\r\n");
      out.write("        \t\t\t\t<p class=\"card-text\">가격도 저렴하고 시설도 깨끗했습니다. 위치도 좋아서 대중교통 이용하기도 편합니다!</p>\r\n");
      out.write("        \t\t\t\t<p class=\"card-text\"><small class=\"text-muted\">Last updated 3 mins ago</small></p>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("      <span>유저 후기로 인증된 신뢰 1위 커뮤니티</span>\r\n");
      out.write("      \r\n");
      out.write("      </section>\r\n");
      out.write("      <section id=\"hindi\">\r\n");
      out.write("      <span>유저 후기로 인증된 신뢰 1위 커뮤니티  </span>\r\n");
      out.write("     \t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"slider.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p id=\"footerp\">&lt;Copyright 2019. <strong>Team Thanos</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/hotel/hotelList\"\r\n");
      out.write("    \tname=\"hotelDataFrm\" id=\"hotelDataFrm\" method=\"post\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t<input type=\"hidden\" name=\"hotelData\" id=\"hotelData\"/>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      slider('.slides');\r\n");
      out.write("      $(\"#searh-button\").click(function(){\r\n");
      out.write("    \t  $.ajax({\r\n");
      out.write("    \t\t\turl:'https://maps.googleapis.com/maps/api/place/textsearch/json?query=hotels+in+london&key=AIzaSyBamfF6Gj9yf1Spt6oL6sX1GB86eMTtI6U',\r\n");
      out.write("    \t\t\ttype:'GET',\r\n");
      out.write("    \t\t\tsuccess: function(data){\r\n");
      out.write("    \t\t\t\t//console.dir(data.results)\r\n");
      out.write("    \t\t\t\tArr =[];\r\n");
      out.write("    \t\t\t\tfor(var i=0; i<3; i++){\r\n");
      out.write("    \t\t\t\t\thotel = {};\r\n");
      out.write("    \t\t\t\t\thotel.id = data.results[i].place_id\r\n");
      out.write("    \t\t\t\t\thotel.name = data.results[i].name\r\n");
      out.write("    \t\t\t\t\tif(data.results[i].photos){\r\n");
      out.write("    \t\t\t\t\thotel.photo = data.results[i].photos[0].photo_reference}\r\n");
      out.write("    \t\t\t\t\thotel.address = data.results[i].formatted_address\r\n");
      out.write("    \t\t\t\t\thotel.rate = data.results[i].rating\r\n");
      out.write("    \t\t\t\t\thotel.info = data.results[i].types\r\n");
      out.write("    \t\t\t\t\tArr.push(hotel)\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t//console.dir(Arr)\r\n");
      out.write("    \t\t\t\tvar json = JSON.stringify(Arr);\r\n");
      out.write("    \t\t\t\t//console.dir(json);\r\n");
      out.write("    \t\t\t\t//param={hotelData:json}\r\n");
      out.write("    \t\t\t\t$(\"#hotelData\").val(json)\r\n");
      out.write("    \t\t\t\t$(\"#hotelDataFrm\").submit()\r\n");
      out.write("    \t\t\t},\r\n");
      out.write("    \t\t\terror:function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("    \t\t\t\tconsole.log(\"ajax처리실패!\")\r\n");
      out.write("    \t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t})\r\n");
      out.write("      })\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
